### ISSUE TITLE
Put this on dockerhub

### ISSUE THREAD

**Issue by LTLA** [iSEE/screenshots#1]
I assume @kevinrue controls the `iseedevelopers` account.

**Comment by kevinrue** [comment]
Done: https://hub.docker.com/repository/docker/iseedevelopers/screenshots

**Comment by kevinrue** [comment]
For what it's worth, the dockerhub organisation includes a "maintainers" group which also includes  @csoneson and @federicomarini , with admin access to the repositories.

@LTLA : Create an account and you can be an admin too
